batch_size: 64
iters: 10000

train_dataset:
  type: Dataset
  dataset_root: data/portrait14k
  transforms:
    - type: Resize
      target_size: [398, 224]
    - type: ResizeStepScaling
      min_scale_factor: 1.0
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [398, 224]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train
  train_path: data/portrait14k/train.txt
  val_path: data/portrait14k/val.txt
  test_path: data/portrait14k/test.txt
  num_classes: 2

val_dataset:
  type: Dataset
  dataset_root: data/portrait14k
  transforms:
    - type: Resize
      target_size: [398, 224]
    - type: Normalize
  mode: val
  train_path: data/portrait14k/train.txt
  val_path: data/portrait14k/val.txt
  test_path: data/portrait14k/test.txt
  num_classes: 2


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.05
  end_lr: 0.0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
