batch_size: 1
iters: 65000

model:
  type: MscaleOCRNet
  pretrained: pretrain/ocrnet_hrnetw48_mapillary_pretrain.pdparams
  n_scales: [0.5,1.0,1.5,2.0,2.5] # more scales
  backbone:
    type: HRNet_W48_NV
  num_classes: 19
  backbone_indices: [0]

val_dataset:
  type: CityscapesAutolabeling
  dataset_root: ../../../../dataset/cityscapes-for-nvidia
  transforms:
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  mode: val
