batch_size: 16
iters: 20000

train_dataset:
  type: Dataset
  dataset_root: data/matting_human_half
  num_classes: 2
  train_path: data/matting_human_half/train.txt
  transforms:
    # - type: Resize
    #   target_size: [600, 800]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: data/matting_human_half
  num_classes: 2
  val_path: data/matting_human_half/val.txt
  transforms:
    - type: Resize
      target_size: [600, 800]
    - type: Normalize
  mode: val

export:
  transforms:
    - type: Resize
      target_size: [600, 800]
    - type: Normalize


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 0.0005

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.1
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]

model:
  type: FCN
  backbone:
    type: HRNet_W18_Small_V1
    align_corners: False
  num_classes: 2
  pretrained: saved_model/fcn_hrnetw18_small_v1_humanseg_192x192_bs64_lr0.1_iter2w_horizontal_distort/best_model/model.pdparams
  backbone_indices: [-1]
