batch_size: 64
iters: 20000

train_dataset:
  type: HumanSeg
  dataset_root: /ssd2/chulutao/humanseg/
  transforms:
    - type: Resize
      target_size: [192, 192]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: HumanSeg
  dataset_root: /ssd2/chulutao/humanseg/
  transforms:
    - type: Resize
      target_size: [192, 192]
    - type: Normalize
  mode: val

export:
  transforms:
    - type: Resize
      target_size: [192, 192]
    - type: Normalize


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 0.0005

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.1
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]

model:
  type: FCN
  backbone:
    type: HRNet_W18_Small_V1
    align_corners: False
  num_classes: 2
  pretrained: Null
  backbone_indices: [-1]
