batch_size: 64
iters: 5000 # about 35 epoch

train_dataset:
  type: Dataset
  dataset_root: data/matting_human_half
  num_classes: 2
  train_path: data/matting_human_half/train.txt
  transforms:
    - type: RandomHorizontalFlip
    - type: Padding
      target_size: [1422, 800]
    - type: Resize
      target_size: [400, 225]
      # target_size: [398, 224]
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: data/matting_human_half
  num_classes: 2
  val_path: data/matting_human_half/val.txt
  transforms:
    # - type: Padding
    #   target_size: [1422, 800]
    - type: Resize
      target_size: [400, 225]
    - type: Normalize
  mode: val

export:
  transforms:
    - type: Padding
      target_size: [1422, 800]
    - type: Resize
      target_size: [400, 225]
    - type: Normalize


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 0.0005

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 1
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
    # - type: CrossEntropyLoss
  coef: [1]

model:
  type: ShuffleNetV2
  align_corners: False
  pretrained: saved_model/shufflenetv2_humanseg_192x192/best_model/model.pdparams
  num_classes: 2
