batch_size: 256
iters: 5000 # about 38 epoch

train_dataset:
  type: HumanSeg
  dataset_root: /ssd2/chulutao/humanseg/
  transforms:
    - type: Resize
      target_size: [192, 192]
    - type: RandomHorizontalFlip
    - type: Normalize
  mode: train

val_dataset:
  type: HumanSeg
  dataset_root: /ssd2/chulutao/humanseg/
  transforms:
    - type: Resize
      target_size: [192, 192]
    - type: Normalize
  mode: val

export:
  transforms:
    - type: Resize
      target_size: [192, 192]
    - type: Normalize


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 0.0005

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 1
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
  coef: [1]

model:
  type: ShuffleNetV2
  align_corners: False
  num_classes: 2
